### ISSUE TITLE
Performance issues after 1.3.4

### ISSUE THREAD

**Issue by kabaaab** [magento/meta-for-magento2#92]
### Preconditions (*)

1. 1.3.4 Adobe Commerce 2.4.5 P9
2.

### Steps to reproduce (*)

1. Upgrade extension to version 1.3.4
2.

### Expected result (*)

1. Performance to be similar to previous versions.
2.

### Actual result (*)

1. Very slow transactions ocasionally causing DB locks and effecting entire site performance.
2. This began to happen after installing version 1.3.4
3. When we view peroids before the 1.3.4 upgrade new relic reports no slow traces.
![screencapture-one-newrelic-nr1-core-apm-features-transactions-MTIwNzYzM3xBUE18QVBQTElDQVRJT058MTE0NTk4ODgxNQ-2024-11-18-11_54_55](https://github.com/user-attachments/assets/540ca22f-9a07-46ad-b42c-201f6344c15a)

**Comment by congrallion** [comment]
I'm facing the same issue

**Comment by kabaaab** [comment]
It's also still an issue in 1.3.5

**Comment by zlik** [comment]
HI @kabaaab, is the issue specific to the `fbe/pixel/tracker` endpoint or is there more slow transactions outside of it?

**Comment by kabaaab** [comment]
Hi @zlik from what i can tell it's specific to the fbe/pixel/tracker

**Comment by kabaaab** [comment]
This is stil an issue in our enviroment newer patches haven't made a difference.

**Comment by congrallion** [comment]
@kabaaab Review your request logs. Bots and crawlers are one of the main reasons for this performance issue. Adding a rule to prevent crawlers from accessing the tracking endpoint fbe/pixel should help

**Comment by pradeepkanaka** [comment]
@kabaaab A new version v1.4.2 has been deployed with fixes to improve performance. Could you please upgrade to the latest version and check if your issue has been resolved?

**Comment by kabaaab** [comment]
Thank you we will updated and i'll report back!

**Comment by kabaaab** [comment]
We have deployed the update.. However it's creating some exceptions and i'm still seeing very long transactions traces for the module; 

/fbe/pixel/tracker/ 103,644 ms and so on;

#0 /chroot/local/automoti/automotivesuperstore.com.au/magento/vendor/meta/module-conversion/Model/Tracker/InitiateCheckout.php(109): Magento\Framework\App\ErrorHandler->handler(2, 'Undefined array...', '/chroot/local/a...', 109)

**Comment by pradeepkanaka** [comment]
@kabaaab Thanks for the feedback. We will look into it.

**Comment by pradeepkanaka** [comment]
@kabaaab Please apply the attached patch to fix the exception

You mentioned /fbe/pixel/tracker/  is taking 103ms & 644ms, could you please let us know which event is taking longer time.

Is this your website? https://automotivesuperstore.com.au/

[meta-undefined-array-key-issue-fix.patch](https://github.com/user-attachments/files/19753853/meta-undefined-array-key-issue-fix.patch)

**Comment by priyambad** [comment]
> We have deployed the update.. However it's creating some exceptions and i'm still seeing very long transactions traces for the module;
> 
> /fbe/pixel/tracker/ 103,644 ms and so on;
> 
> #0 /chroot/local/automoti/automotivesuperstore.com.au/magento/vendor/meta/module-conversion/Model/Tracker/InitiateCheckout.php(109): Magento\Framework\App\ErrorHandler->handler(2, 'Undefined array...', '/chroot/local/a...', 109)

@kabaaab, since this issue is fixed already, I would close this ticket for now.
We understand that you are facing some performance issue specifically in the fbe/pixel/tracker endpoint.
We are implementing message queue for the backend events which would fix the performance issues.
That would be tracked in https://github.com/magento/meta-for-magento2/issues/20, and the changes should be available in next release.
